spring.application.name=auth-service


server.port=9100

server.servlet.context-path=/uaa

#address of the naming server to be able to register/discover other microservices
eureka.client.service-url.default-zone=http://localhost:8761

#postgresql
spring.datasource.url=jdbc:postgresql://localhost/investorbook
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

investorbook.security.jwt.public.key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+GGXOyXKtJtMJyiWV0+8GG2htO0tPXXLgf7Kk5OfP4sXR2lfHd7sGmo1baMho+yAyyE7lay663PfHe0jVGOEHApHAorrxP88EE7pvlyjGYq7OviQmRaEDKStgdVyEKqX9Ho+5GkFr0PL6n7biGkTaTWn1VrxqOFQdmr/thwYi/L/ZLON6zWODW4A0nqW9EbF+cZPFWr96NGVULTfMzxYQk6bpDFn0odGn8caUXsrG5GC2M2Yj3efeFW6nCwXhlCUfDJhvzIbBWpktY+hSMKUNPhqkOILetqJuoEWX3zi1YfUarusC/1MKUPYN6vgoaLJnmqlXIE8c3pfnLpAGfHIwQIDAQAB-----END PUBLIC KEY-----
investorbook.security.jwt.private.key=-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEA+GGXOyXKtJtMJyiWV0+8GG2htO0tPXXLgf7Kk5OfP4sXR2lfHd7sGmo1baMho+yAyyE7lay663PfHe0jVGOEHApHAorrxP88EE7pvlyjGYq7OviQmRaEDKStgdVyEKqX9Ho+5GkFr0PL6n7biGkTaTWn1VrxqOFQdmr/thwYi/L/ZLON6zWODW4A0nqW9EbF+cZPFWr96NGVULTfMzxYQk6bpDFn0odGn8caUXsrG5GC2M2Yj3efeFW6nCwXhlCUfDJhvzIbBWpktY+hSMKUNPhqkOILetqJuoEWX3zi1YfUarusC/1MKUPYN6vgoaLJnmqlXIE8c3pfnLpAGfHIwQIDAQABAoIBAFdnUCZ6OAiyFWw6Nh1na5NVEPBv/dmA2CpYlMS1z/Y2Zey1QclrJr5s3XxFSZM7qF7SxPr4m5Y7YipPxnztwBF19GMKq8jY4DQE8PAR/TsBvL0VtxyH9dPVJ1Fm4QrIXUykr/kElAGG4/0SwwIPp8sAHJ1RsXRyRTRGltFotaKZIJc/EymoxZL1Out8NA7snLL+V6OSFEYnY762H8RrWLFV+F0jFLIG7Km86pcpo32kD7sS+7iEOwJmRQmJqhrCHPgNJivh+MkD8zH6jhXIsbLEbJ1BY3k4QHmqQP8JWyxUGFbeGCLAjeD2GslZWqm4lGg5fhAiQRwXNsyeIngbMtkCgYEA/tMV19bRWxhURBGmsRh4cdgeitqR+vGjpAz3goWMTZpatRHYzlKNK2lHr2jzrr2wfUm44yXmhjizE08j8kKiyOkULnaN9e7pPnkrhHRNTwouJZBBuYIyjvx4By7XBCUTPgjXAVJ4A+qpf7CUVNflF7zoZ3aHwcy4OfVFWTZ1GqcCgYEA+YbljJmZKDFjvBRKheStzu4BEwAEo2jllyZHx7QdFKlBV1cvwGfv/0bR9RYsCFR4gZsKEMZvKJUeB+ZSdNQBXOaXro35MIhdiV1AWJdf2hj7yOFM8oAKgtA1vh6pQ6m8k/OpC8c2BH4NujIxlnRuTXTstvb0bPjD73xJmQyVtlcCgYBEIEjZsHu+H+3/WLy44fLpdL8NnkuizFFUfYb6ZRvSb27Ks9/DoTxOm9Hnamajk+EITdpZF/vebHArvF++1+PPVMjpdxaS5nGDGz/wJGu6st0Ne9imcNF1erfYK8SePg876X8ZwmOFoIn6MkoluKZtxzpW1tCKlmG2VQVaSX3bRwKBgDIGlHDavnTrafZkDwjG7v2kg7yebU+hkR37g7qK5qWkxT/Qb/dgHyKLvT4oos1Muhgp0BvK3LBDLREiYPehJWDNri1Fs2bCgBYxBtx8BLCB/8CnQrj/aJwPSCcEmKTDG9aBrCt7Vd4Ss4fX1k82qoKG5YpM+nX6bbXOsian+j/jAoGBAPINNCTUyp8W7rVHbmhYS4jQ86lB8/J3/+voaVKg/eCw/N/D9xaZBcm+NH1qtF/PRyYNnpzo8CwKsWVN4Yb9ZmJD/A0W/j6c2m7tkVngSdduhteTOn6ZWMJ1Oe60aYRWeEgjBmmw2E0LpGCWbPMe9VBb7DBluAkYMdzUEpoEpvHU-----END RSA PRIVATE KEY-----

investorbook.security.html5.jwt.client.id=html5

#html5secretpass123
investorbook.security.html5.jwt.client.secret=$2a$10$UDpOBf6eXtZcC2ix9DXJEuIGJXd0unhLoPw82JfK5ftYEnE.mxP1i