spring.application.name=authentication-service


server.port=8200


#address of the naming server to be able to register/discover other microservices
eureka.client.service-url.default-zone=http://localhost:8761