
spring.application.name=signup-service


server.port=8100


#address of the naming server to be able to register/discover other microservices
eureka.client.service-url.default-zone=http://localhost:8761
