
spring.application.name=test-service

server.port=8000

#address of the naming server to be able to register/discover other micro services
eureka.client.service-url.default-zone=http://localhost:8761

#eureka.client.service-url.default-zone=http://peer1:8761,http://peer2:8762
